#!/bin/env bash

# get to parent directory
BASEDIR=`cd ..; pwd`

# setup vim, download vundle plugin manager, and install plugins
ln -s ${BASEDIR}/vimrc ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# git
ln -s ${BASEDIR}/gitconfig ~/.gitconfig
